source 'https://github.com/CocoaPods/Specs.git'
    platform :ios, '10.0'
use_frameworks!

target "techchallenge_jingluo" do
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'Alamofire', '~> 4.5'
    pod 'Kingfisher', '~> 4.0'
    pod 'ObjectMapper', '~> 3.1'
    pod 'SwiftIcons', '~> 2.0.1'
end

target "techchallenge_jingluoTests" do
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'ObjectMapper', '~> 3.1'
end
